# Generated by Django 4.0.4 on 2022-05-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connectedRealmsIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectedId', models.DecimalField(decimal_places=0, help_text='Id for the connected realms', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='itemBonus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('effect', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
            ],
        ),
        migrations.CreateModel(
            name='professionIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='professionTeir',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionindex')),
            ],
        ),
        migrations.CreateModel(
            name='recipeCatagory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('professionIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionindex')),
                ('professionTeir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionteir')),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mats', models.ManyToManyField(to='calculator.material')),
                ('product', models.ManyToManyField(to='calculator.item')),
                ('professionIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionindex')),
                ('professionTeir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionteir')),
                ('recipeCatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recipecatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('realmId', models.DecimalField(decimal_places=0, help_text='Realm specific id', max_digits=4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Illidan, Stormrage, ...', max_length=30)),
                ('population', models.CharField(choices=[('Low', 'Low'), ('Med', 'Medium'), ('High', 'High'), ('Full', 'Full')], help_text='Low, Medium, High, Full', max_length=20)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('LA', 'Latin America'), ('SA', 'South America'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('EU', 'European Union'), ('EE', 'Eastern Europe'), ('RU', 'Russia'), ('AF', 'Africa'), ('ME', 'Middle East'), ('SK', 'South Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('MU', 'Macau')], help_text='North America, Europe, ...', max_length=30)),
                ('timezone', models.CharField(max_length=40)),
                ('type', models.CharField(help_text='Normal, RP, PVP, PVPRP', max_length=20)),
                ('connectedRealmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
            ],
        ),
        migrations.CreateModel(
            name='auction',
            fields=[
                ('auctionId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('buyout', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=7)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('connectedRealmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
                ('itemBonusList', models.ManyToManyField(to='calculator.itembonus')),
            ],
        ),
    ]
