# Generated by Django 4.0.4 on 2022-06-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedRealmsIndex',
            fields=[
                ('connected_realm_id', models.IntegerField(help_text='Id for the connected realms', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBonus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionTeir',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionindex')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCatagory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('profession_teir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.professionteir')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mats', models.ManyToManyField(to='calculator.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
                ('recipeCatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recipecatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('population', models.CharField(choices=[('Low', 'Low'), ('Med', 'Medium'), ('High', 'High'), ('Full', 'Full')], help_text='Low, Medium, High, Full', max_length=20)),
                ('realm_id', models.DecimalField(decimal_places=0, help_text='Realm specific id', max_digits=4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Illidan, Stormrage, ...', max_length=30)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('LA', 'Latin America'), ('SA', 'South America'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('EU', 'European Union'), ('EE', 'Eastern Europe'), ('RU', 'Russia'), ('AF', 'Africa'), ('ME', 'Middle East'), ('SK', 'South Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('MU', 'Macau')], help_text='North America, Europe, ...', max_length=30)),
                ('timezone', models.CharField(max_length=40)),
                ('play_style', models.CharField(help_text='Normal, RP', max_length=7)),
                ('connected_realm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('buyout', models.IntegerField(blank=True, null=True)),
                ('bid', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('connected_realm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
                ('item_bonus_list', models.ManyToManyField(to='calculator.itembonus')),
            ],
        ),
    ]
