# Generated by Django 4.0.4 on 2022-05-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='professionIndex',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='professionTeir',
        ),
        migrations.RemoveField(
            model_name='recipecatagory',
            name='professionIndex',
        ),
    ]
