# Generated by Django 4.0.4 on 2022-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodifier',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmodifier',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
