# Generated by Django 4.0.4 on 2022-06-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rename_connected_realm_id_realm_connected_realm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realm',
        ),
    ]
