# Generated by Django 4.1.4 on 2023-01-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_alter_auction_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="buyout",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bonuslist",
            name="id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.itemtier",
            ),
        ),
        migrations.AlterField(
            model_name="modifierlist",
            name="id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
