# Generated by Django 4.0.4 on 2022-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_itemmodifier_type_alter_itemmodifier_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodifier',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodifier',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
