# Generated by Django 4.0.4 on 2022-06-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_itemmodifier_type_alter_itemmodifier_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModifier',
        ),
    ]
