# Generated by Django 4.0.4 on 2022-06-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_delete_realm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('population', models.CharField(choices=[('Low', 'Low'), ('Med', 'Medium'), ('High', 'High'), ('Full', 'Full')], help_text='Low, Medium, High, Full', max_length=20)),
                ('realm_id', models.DecimalField(decimal_places=0, help_text='Realm specific id', max_digits=4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Illidan, Stormrage, ...', max_length=30)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('LA', 'Latin America'), ('SA', 'South America'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('EU', 'European Union'), ('EE', 'Eastern Europe'), ('RU', 'Russia'), ('AF', 'Africa'), ('ME', 'Middle East'), ('SK', 'South Korea'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('MU', 'Macau')], help_text='North America, Europe, ...', max_length=30)),
                ('timezone', models.CharField(max_length=40)),
                ('play_style', models.CharField(help_text='Normal, RP', max_length=7)),
                ('connected_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
            ],
        ),
    ]
