# Generated by Django 4.0.4 on 2022-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_delete_itemmodifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
