# Generated by Django 4.1.4 on 2023-01-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_modifierkey_modifierpair_modifiervalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipecategory",
            old_name="profession_tier",
            new_name="profession",
        ),
        migrations.AddField(
            model_name="auction",
            name="region",
            field=models.ForeignKey(
                default="us",
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.region",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="connected_realm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.connectedrealmsindex",
            ),
        ),
    ]
