# Generated by Django 4.0.4 on 2022-06-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_auction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='connected_realm_id',
            new_name='connected_realm',
        ),
    ]
