# Generated by Django 4.1.4 on 2023-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0006_modifiedcraftingitem_modifiedcraftingspellslot_spell_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CraftingQuality",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("quality", models.IntegerField()),
            ],
        ),
    ]
