# Generated by Django 4.1.4 on 2023-01-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0007_craftingquality"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CraftingStats",
        ),
    ]
