# Generated by Django 4.0.4 on 2022-06-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_alter_recipecatagory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeCatagory',
            new_name='recipe_catagory',
        ),
    ]
