# Generated by Django 4.1.4 on 2023-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_craftingstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craftingstats",
            name="crafting_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="craftingstats",
            name="increase_material_from_resourcefulness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="craftingstats",
            name="skill_from_inspiration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
