# Generated by Django 4.1.4 on 2023-01-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_alter_craftingstats_crafting_speed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CraftingQuality",
        ),
        migrations.DeleteModel(
            name="ModifiedCraftingItem",
        ),
        migrations.DeleteModel(
            name="ModifiedCraftingSpellSlot",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="max_quantity",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="craftingstats",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_quantity",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="spell",
        ),
        migrations.DeleteModel(
            name="Spell",
        ),
    ]
