# Generated by Django 4.0.4 on 2022-06-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_rename_recipecatagory_recipe_recipe_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeCatagory',
            new_name='RecipeCategory',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_catagory',
            new_name='recipe_category',
        ),
    ]
