# Generated by Django 4.0.4 on 2022-06-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_rename_recipecatagory_recipecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.item'),
        ),
    ]
