# Generated by Django 4.1.4 on 2023-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0012_recipe_item_recipe_quantity_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionalmaterialslot",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
