# Generated by Django 4.1.4 on 2023-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0013_alter_optionalmaterialslot_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
