# Generated by Django 4.0.4 on 2022-06-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_recipe_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
