# Generated by Django 4.1.4 on 2023-02-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0014_alter_recipe_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="item",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="quantity",
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.item",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.recipe",
                    ),
                ),
            ],
        ),
    ]
