# Generated by Django 4.0.4 on 2022-06-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_alter_realm_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionindex',
            options={'ordering': ['id']},
        ),
    ]
