# Generated by Django 4.0.4 on 2022-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_alter_professiontier_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professiontier',
            options={'ordering': ['profession', 'id']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='professiontier',
            order_with_respect_to=None,
        ),
    ]
