# Generated by Django 4.1.4 on 2023-04-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0018_alter_modifiedcraftingreagentslot_modified_crafting_category",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Testificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "testificate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="calculator.testificate",
                    ),
                ),
                ("child", models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=("calculator.testificate",),
        ),
    ]
