# Generated by Django 4.0.4 on 2022-06-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_alter_professionindex_name_alter_professiontier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recipe')),
            ],
        ),
    ]
