# Generated by Django 4.1.4 on 2023-04-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0019_testificate_baby"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Baby",
        ),
        migrations.DeleteModel(
            name="Testificate",
        ),
    ]
