# Generated by Django 4.1.4 on 2023-04-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0020_delete_baby_delete_testificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="optional_material_slot",
        ),
        migrations.CreateModel(
            name="OptionalMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("recraft_quantity", models.IntegerField(blank=True, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "optional_material_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.optionalmaterialslot",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.recipe",
                    ),
                ),
            ],
        ),
    ]
