# Generated by Django 4.0.4 on 2022-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0021_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_max',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
