# Generated by Django 4.1.4 on 2023-04-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0021_remove_material_optional_material_slot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="name",
        ),
        migrations.RemoveField(
            model_name="optionalmaterial",
            name="name",
        ),
        migrations.AddField(
            model_name="material",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="optionalmaterial",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.item",
            ),
            preserve_default=False,
        ),
    ]
