# Generated by Django 4.1.4 on 2023-04-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0022_remove_material_name_remove_optionalmaterial_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optionalmaterial",
            name="item",
        ),
    ]
