# Generated by Django 4.0.4 on 2022-06-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0022_rename_quantity_product_quantity_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_max',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_min',
            new_name='min_quantity',
        ),
    ]
