# Generated by Django 4.1.4 on 2023-04-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0023_remove_optionalmaterial_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryReagentSlotRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.modifiedcraftingcategory",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="MCR_item",
        ),
        migrations.RemoveField(
            model_name="modifiedcraftingreagentslot",
            name="modified_crafting_category",
        ),
        migrations.AddField(
            model_name="item",
            name="modified_crafting_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.modifiedcraftingcategory",
            ),
        ),
        migrations.AlterField(
            model_name="optionalmaterial",
            name="optional_material_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.modifiedcraftingreagentslot",
            ),
        ),
        migrations.DeleteModel(
            name="ModifiedCraftingReagentItem",
        ),
        migrations.DeleteModel(
            name="OptionalMaterialSlot",
        ),
        migrations.AddField(
            model_name="categoryreagentslotrelationship",
            name="reagent_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="categories",
                to="calculator.modifiedcraftingreagentslot",
            ),
        ),
    ]
