# Generated by Django 4.0.4 on 2022-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0023_rename_quantity_max_product_max_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_left',
            field=models.CharField(max_length=20),
        ),
    ]
