# Generated by Django 4.0.4 on 2022-06-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_alter_auction_time_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
