# Generated by Django 4.1.4 on 2023-04-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0024_categoryreagentslotrelationship_remove_item_mcr_item_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifiedCraftingReagentItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "modified_crafting_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.modifiedcraftingcategory",
                    ),
                ),
            ],
        ),
    ]
