# Generated by Django 4.0.4 on 2022-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0025_alter_auction_auction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='buyout',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unit_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
