# Generated by Django 4.1.4 on 2023-04-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0025_modifiedcraftingreagentitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="modified_crafting_category",
        ),
        migrations.AddField(
            model_name="item",
            name="MCR_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.modifiedcraftingreagentitem",
            ),
        ),
    ]
