# Generated by Django 4.1.4 on 2023-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0026_remove_item_modified_crafting_category_item_mcr_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifiedcraftingcategory",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="modifiedcraftingcategory",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="CraftingStats",
        ),
    ]
