# Generated by Django 4.0.4 on 2022-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0027_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembonus',
            name='auctions',
        ),
        migrations.AddField(
            model_name='auction',
            name='bonuses',
            field=models.ManyToManyField(blank=True, to='calculator.itembonus'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='connectedrealmsindex',
            name='connected_realm_id',
            field=models.IntegerField(db_index=True, help_text='Id for the connected realms', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itembonus',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
