# Generated by Django 4.0.4 on 2022-07-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_remove_itembonus_auctions_auction_bonuses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModifier',
        ),
    ]
