# Generated by Django 4.0.4 on 2022-07-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0029_delete_itemmodifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(help_text='North America, Europe, ...', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='binding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_buy_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_sell_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('profit', models.IntegerField()),
                ('connected_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_median_mp', models.IntegerField()),
                ('region_avg_mp', models.IntegerField()),
                ('region_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.region')),
            ],
        ),
        migrations.AlterField(
            model_name='realm',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.region'),
        ),
    ]
