# Generated by Django 4.1.4 on 2023-04-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0029_craftingstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionEffectType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionEffect",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                (
                    "MCR_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.modifiedcraftingreagentslot",
                    ),
                ),
                (
                    "profession_effect_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.professioneffecttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CraftingReagentEffect",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("order", models.IntegerField()),
                (
                    "modified_crafting_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.modifiedcraftingcategory",
                    ),
                ),
                (
                    "profession_effect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.professioneffect",
                    ),
                ),
            ],
        ),
    ]
