# Generated by Django 4.1.4 on 2023-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0030_professioneffecttype_professioneffect_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professioneffect",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
