# Generated by Django 4.0.4 on 2022-08-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0030_region_item_binding_item_quality_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceData',
            new_name='RegionPriceData',
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_buy_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='population',
            field=models.CharField(help_text='Low, Medium, High, Full', max_length=20),
        ),
        migrations.CreateModel(
            name='RealmPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_mp', models.IntegerField()),
                ('avg_mp', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('connected_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.connectedrealmsindex')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.item')),
            ],
        ),
    ]
