# Generated by Django 4.1.4 on 2023-05-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0031_alter_professioneffect_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professioneffect",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CraftingReagentQuality",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("difficulty_adjustment", models.IntegerField(blank=True, null=True)),
                ("reagent_effect_percent", models.IntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.item",
                    ),
                ),
                (
                    "modified_crafting_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.modifiedcraftingcategory",
                    ),
                ),
            ],
        ),
    ]
