# Generated by Django 4.0.4 on 2022-08-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0031_rename_pricedata_regionpricedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.IntegerField(help_text='Realm specific id', primary_key=True, serialize=False),
        ),
    ]
