# Generated by Django 4.1.4 on 2023-05-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0033_itemtype_item_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="craftingstats",
            name="id",
        ),
        migrations.AlterField(
            model_name="categoryreagentslotrelationship",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="craftingstats",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="calculator.item",
            ),
        ),
        migrations.AlterField(
            model_name="professionindex",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=("item", "recipe"), name="unique_material"
            ),
        ),
        migrations.AddConstraint(
            model_name="optionalmaterial",
            constraint=models.UniqueConstraint(
                fields=("recipe", "optional_material_slot"),
                name="unique_optional_material",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("item", "recipe"), name="unique_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipecategory",
            constraint=models.UniqueConstraint(
                fields=("name", "profession"), name="unique_category"
            ),
        ),
    ]
